### ISSUE TITLE
don't work with quiz user overrides

### ISSUE THREAD

**Issue by ykmnkmi** [examus/moodle-availability_examus#25]
Rewriting attempts for some students in quiz, ```* Student does not have the correct group or role to attempt the quiz```

**Comment by MaksimBurnin** [comment]
Hello
Can you provide a bit more details? 

1. What version of Examus plugin you are currently using?
2. What version of Moodle are you using?
3. What happened before the issue started to occur? (e.g. moodle version was updated)
4. Which organization do you represent?

**Comment by ykmnkmi** [comment]
1. What version of Examus plugin you are currently using?
```php
$version  = 2018120303.15;
$release  = '3.6.3+ (Build: 20190503)';
```
2. What version of Moodle are you using?
```php
$plugin->version = 2019112502;
$plugin->release = 'v3.1-r4';
$plugin->requires = 2016052300;
$plugin->maturity = MATURITY_STABLE;
```
3. What happened before the issue started to occur?
Not used before, quiz duplication or remove last attempts.

4. Which organization do you represent?
Almaty Management University
